### ISSUE TITLE
初回起動時の/にアクセすると502 Bad Gatewayが表示する

### ISSUE THREAD

**Issue by akira1908jp** [ytnobody/docker-revealup#1]
初回の起動時に/にアクセスすると,502 Bad Gatewayが表示する

**Comment by ytnobody** [comment]
これ、どう対応しますかねえ。
マネージャーにでもリダイレクトするようにします？

**Comment by akira1908jp** [comment]
任意にmdを読み込んでいない場合は、index.mdみたい表示するだけのテンプレートを設定しておけばよいかと思います。

index.mdの中にリンクの/manegerを入れとけば、表示確認と遷移が使いやすいと思いますよ。
