### ISSUE TITLE
input set size optiion

### ISSUE THREAD

**Issue by akira1908jp** [ytnobody/docker-revealup#5]
set option width,height.

**Comment by ytnobody** [comment]
http://search.cpan.org/~yusukebe/App-revealup-0.19/lib/App/revealup/cli/serve.pm#Options この辺に対応すればいいすかね。

**Comment by akira1908jp** [comment]
そうですね。
できれば4:3,16:9に出来れば良いと思います.

**Comment by ytnobody** [comment]
702633f0d7c3e9eabed5a68d61a647f5679f0e85 あたりで雑に追加してみました

**Comment by akira1908jp** [comment]
[![LGTM](http://lgtm.in/p/oyzr4VD6q)](http://lgtm.in/i/oyzr4VD6q)
